version: '3.8'

services:
  pg-master:
    build: .
    image: replication-pg-master
    container_name: pg-master
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - /var/lib/postgresql/data_smstracker_master:/var/lib/postgresql/data
    expose:
     - '5432'
    ports:
     - '5432:5432'
