version: '3.8'

services:
  pg-slave:
    build: .
    image: replication-pg-slave
    container_name: pg-slave
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: '172.31.19.194'
    volumes:
     - /var/lib/postgresql/data_smstracker_slave:/var/lib/postgresql/data
    expose:
     - '5432'
    ports:
     - '5434:5432'
