version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=digital_journey
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
