version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "fintech-aggregator-execution-request:1:1,fintech-aggregator-report-service:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    expose:
      - 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none

  kowl:
    image: quay.io/cloudhut/kowl:latest
    restart: on-failure
    hostname: kowl
    volumes:
    - ./config.yaml:/etc/kowl/config.yaml
    ports:
    - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka


# version: "3.8"

# services:
#   zookeeper:
#     image: docker.io/bitnami/zookeeper:3.8
#     ports:
#       - "2181:2181"
#     volumes:
#       - "zookeeper_data:/bitnami"
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: docker.io/bitnami/kafka:3.1
#     ports:
#       - "9092:9092"
#     volumes:
#       - "kafka_data:/bitnami"
#     environment:  
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#     depends_on:
#       - zookeeper

# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local
