version: '3.8'

services:
  redis:
    image: redis:4.0.1-alpine
    container_name: redis
    restart: 'unless-stopped'
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
    expose:
      - '6379'
    ports:
      - '6379:6379'
    command: redis-server --requirepass password
