version: '3.8'

services:
  mysql:
    image: mysql:5.7.34
    container_name: temporal_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: "--character-set-server=utf8mb4 --max-connections=100000 --sql-mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"

  temporal:
    image: temporalio/auto-setup:1.13.1
    container_name: temporal
    depends_on:
      - mysql
    environment:
      DB: mysql
      DB_PORT: 3306
      MYSQL_USER: root
      MYSQL_PWD: password
      MYSQL_SEEDS: mysql
    ports:
      - "7233:7233"
  temporal_web:
    image: temporalio/web:latest
    depends_on:
      - temporal
    ports:
      - "8088:8088"


